steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/lima-consulting-prd/api-fastapi/api-extract:latest', '.']

  # Push da imagem para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/lima-consulting-prd/api-fastapi/api-extract:latest']

images:
  # Imagem a ser enviada para o Container Registry
  - 'gcr.io/lima-consulting-prd/api-fastapi/api-extract'