# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run the FastAPI application with Uvicorn when the container starts
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8080"]
